### ISSUE TITLE
xpath 2.0 support

### ISSUE THREAD

**Issue by TimHeap46** [uli-weltersbach/XPathTools#26]
Hi Uli, are there any plans to support xpath 2.0 or 3.0 going forward ? I really like the tool but it doesn't work for us at the moment because we need to able to support xpath 2.0

**Comment by uli-weltersbach** [comment]
Currently I'm using the standard .NET library for XPath queries, which doesn't support 2.0+.
If you have a recommendation reg. a free .NET framework which supports XPath 2.0+ I'd be happy to use that instead of standard .NET.

**Comment by uli-weltersbach** [comment]
Further consideration: people working with .NET apps might be confused when their XPath 2.0+ queries work in the XPath Runnner, but not in their XSLTs, XDTs, ASP.NET apps etc.

**Comment by uli-weltersbach** [comment]
I'm closing this due to a lack of feedback from @TimHeap46 .

**Comment by TimHeap46** [comment]
Hi Uli, we've found a different solution. Thanks for your help.
