### ISSUE TITLE
Runner to query by simple path when file has a namespace

### ISSUE THREAD

**Issue by tig2810** [uli-weltersbach/XPathTools#27]
Hi,

We can query the simple path with 'Copy XPath > last element in the context menu', but if we then paste this into the runner, it will not locate the value in the element when the xml file has a namespace.  

![2018-05-10_17-59-50](https://user-images.githubusercontent.com/13333006/39882621-346d2fec-547c-11e8-8af8-b3f1f513e3a8.jpg)

**Comment by uli-weltersbach** [comment]
Thanks for the feedback! 
Could you include your XML sample (so I don't have to type it in manually from the screenshot)?

**Comment by uli-weltersbach** [comment]
Hi

You're explicitly copying the XPath WITHOUT the XMLNS, so the behavior is expected.
See https://github.com/uli-weltersbach/XPathTools/wiki/Copying-XPaths#copy-xpath-excl-xmlns for details, particularly the part about "**Zero** or more results".

**Comment by tig2810** [comment]
Hi,
Yes I understand that, but I dont think it's such a realistic use case.   It's also the default for XML Spy as in the screenshot. 
![2018-05-11_11-24-52](https://user-images.githubusercontent.com/13333006/39920167-1313a1d6-550e-11e8-9792-747efb50e5d8.jpg)

**Comment by uli-weltersbach** [comment]
The feature was explicitly requested like this, so it's a use case brought on by a concrete business need from other users.

I've never used Altova XML Spy, and I've never aimed at copying the features of other software out there, so if Altova XML Spy works for you, you should stick with that.
