### ISSUE TITLE
Not working in valid XHTML file

### ISSUE THREAD

**Issue by Relax594** [uli-weltersbach/XPathTools#29]
This is by definition valid XHTML code and the w3 validator confirms that. However the Extension is not showing up in ContextMenu.

FileName: abc.xhtml

`<?xml version="1.0" encoding="UTF-8" ?>`
`<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">`
`<html xmlns="http://www.w3.org/1999/xhtml">`

`<head>`
    `<title>Online</title>`
    `<script type="text/javascript" src="masken/includes/js/j-0.js">//</script>`
    `<script type="text/javascript" src="masken/includes/js/g-0.js">//</script>`
    `<link rel="stylesheet" type="text/css" href="masken/includes/css/g-0.css" />`
`</head>`

`<body onload="javascript:setup();">`

    <form id="daten" action="{{{Intern_FORMACTION}}}" method="post">
        <div id="aussendiv">
            <input name="Z0000" type="hidden" value="7" />
        </div>
    </form>
`</body>`
`</html>`

**Comment by uli-weltersbach** [comment]
You have to open the file using the "XML (Text) Editor".
If you don't want to change the default Editor File Associations in Visual Studio, you can do the following:

1. Open the context menu (usually bound to the right mouse button) and select "Open with...":

![open_with](https://user-images.githubusercontent.com/1416006/47884845-ab642c00-de32-11e8-8d63-dfdd13e97007.png)

2.  Select "XML (Text) Editor":

![open_with_step_2](https://user-images.githubusercontent.com/1416006/47884887-d5b5e980-de32-11e8-8e3c-f9cd518a8f30.png)

3. Enjoy & [consider rating the extension on the Visual Studio Marketplace](https://marketplace.visualstudio.com/items?itemName=UliWeltersbach.XPathInformation):

![open_with_step_3](https://user-images.githubusercontent.com/1416006/47884954-157cd100-de33-11e8-86da-d8babcb0908f.png)
