### ISSUE TITLE
Copy XML Structure keeps white spaces

### ISSUE THREAD

**Issue by mikaelnet** [uli-weltersbach/XPathTools#34]
The "Copy XML Structure" is one of my favorite commands in this tool. However it keeps a lot of white spaces when this operation is performed. (One of the earlier releases of XPathTools didn't do this.)

I suggest empty lines (containing just white space characters) to be omitted from the code copied to the clip board.

**Comment by uli-weltersbach** [comment]
Hi @mikaelnet 
Thanks for reporting this issue. 
A fix will be available within the hour :)
