### ISSUE TITLE
VS2019 Support?

### ISSUE THREAD

**Issue by iccfish** [uli-weltersbach/XPathTools#36]
Please consider support for vs2019, Thanks 😄

**Comment by uli-weltersbach** [comment]
Thanks for the heads up, will get right on it :D

**Comment by uli-weltersbach** [comment]
Seems like it will be necessary to change the "load behavior" of the extension, otherwise it won't work in Visual Studio 2019, version 16.1:

https://blogs.msdn.microsoft.com/visualstudio/2018/05/16/improving-the-responsiveness-of-critical-scenarios-by-updating-auto-load-behavior-for-extensions/

**Comment by iccfish** [comment]
Yep....Since 2017 MS has added a set of AsyncPackage in order to improve load speed. Class 'Package' and initialization method 'Initialize' needs to
be replaced with 'AsyncPackage' and 'InitializeAsync'.

Emm....Seems that ms always changing something 😄
