### ISSUE TITLE
Can't install from vsix

### ISSUE THREAD

**Issue by tapin13** [uli-weltersbach/XPathTools#45]
Download file from https://marketplace.visualstudio.com/items?itemName=UliWeltersbach.XPathInformation

Go to "Download from vsix".

Get error: "extension/package.json not found inside zip."

VSC: 1.41.0 Linux Debian.

**Comment by uli-weltersbach** [comment]
This is not a Visual Studio Code extension.

**Comment by tapin13** [comment]
Sorry.
