### ISSUE TITLE
Challenges Installing in VS2017 Pro

### ISSUE THREAD

**Issue by jasonCodesAway** [uli-weltersbach/XPathTools#48]
Greetings! This looks awesome and has works for so many. My IT department installed VS2017 and they're known to do some interesting things. Any idea what might have caused this install error? I tried both from within VS's "Extension and Updates" and by downloading and running the latest ReasonCodeExample.XPathTools.vsix - same result. Thank you!

![image](https://user-images.githubusercontent.com/14617506/126194057-af8ff28a-a3b5-4e1c-866f-0636c882b178.png)

[VS 2017 Info.txt](https://github.com/uli-weltersbach/XPathTools/files/6842497/VS.2017.Info.txt)

**Comment by uli-weltersbach** [comment]
Hi @jasonCodesAway!
Never seen an error like that.
Are you seeing similar issues when installing other Extensions from the Marketplace?
