### ISSUE TITLE
cs5001

### ISSUE THREAD

**Issue by Navya170429** [uli-weltersbach/XPathTools#50]
CS5001 C# Program does not contain a static 'Main' method suitable for an entry point

**Comment by Navya170429** [comment]
not PLANNED means

**Comment by uli-weltersbach** [comment]
Sorry, honestly thought this was an issue created by a bot 😆 
In case you're a human, please [add more details](https://www.google.com/search?q=how+to+write+a+good+bug+report) to whatever it is you're reporting.
